# Generated by Django 4.2 on 2023-04-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=13, unique=True)),
                ('identifier', models.CharField(max_length=13)),
                ('organ_id', models.CharField(max_length=13)),
                ('file_catalog', models.IntegerField()),
                ('file_notation', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=1000)),
                ('maintenance', models.CharField(max_length=100)),
                ('rights', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_doc', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('infor_sign', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=100)),
                ('sheet_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('format', models.CharField(max_length=50)),
                ('extra_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(max_length=13)),
                ('identifier', models.CharField(max_length=13)),
                ('organ_id', models.CharField(max_length=13)),
                ('file_catalog', models.IntegerField()),
                ('file_notation', models.CharField(max_length=20)),
                ('doc_ordinal', models.IntegerField()),
                ('type_name', models.CharField(max_length=100)),
                ('code_number', models.CharField(max_length=11)),
                ('code_notation', models.CharField(max_length=30)),
                ('issued_date', models.DateField()),
                ('organ_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=100)),
                ('page_amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('infor_sign', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=20)),
                ('confidence_level', models.CharField(max_length=30)),
                ('autograph', models.CharField(max_length=2000)),
                ('format', models.CharField(max_length=50)),
                ('file_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_storage.file', to_field='file_code')),
            ],
        ),
    ]
