# Generated by Django 4.2 on 2023-04-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=13)),
                ('identifier', models.CharField(max_length=13)),
                ('organ_id', models.CharField(max_length=13)),
                ('file_catalog', models.IntegerField()),
                ('file_notation', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=1000)),
                ('maintenance', models.CharField(max_length=100)),
                ('rights', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_doc', models.IntegerField()),
                ('description', models.CharField(max_length=2000)),
                ('infor_sign', models.CharField(max_length=30)),
                ('keyword', models.CharField(max_length=100)),
                ('sheet_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('format', models.CharField(max_length=50)),
                ('extra_info', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file_code',
            field=models.CharField(max_length=13),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
