# Generated by Django 4.2 on 2023-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_govfile_alter_document_file_code_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govfile',
            name='file_catalog',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='govfile',
            name='page_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='govfile',
            name='sheet_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='govfile',
            name='total_doc',
            field=models.IntegerField(null=True),
        ),
    ]
