# Generated by Django 4.2 on 2023-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_alter_govfile_file_catalog_alter_govfile_page_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_ordinal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_catalog',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='issued_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='page_amount',
            field=models.IntegerField(null=True),
        ),
    ]
