# Generated by Django 4.2 on 2023-04-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_alter_document_doc_ordinal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_code',
            new_name='file_id',
        ),
        migrations.RenameField(
            model_name='govfile',
            old_name='file_code',
            new_name='file_id',
        ),
    ]
