# Generated by Django 4.2 on 2023-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_rename_file_code_document_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govfile',
            name='identifier',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='govfile',
            name='organ_id',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
