# Generated by Django 4.2 on 2023-04-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0007_alter_govfile_description_alter_govfile_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_path',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
