from django.db import models


class GovFile(models.Model):
    file_id = models.CharField(max_length=13)
    identifier = models.CharField(max_length=13, null=True)
    organ_id = models.CharField(max_length=13, null=True)
    file_catalog = models.IntegerField(null=True)
    file_notation = models.CharField(max_length=20, null=True)
    title = models.CharField(max_length=1000, null=True)
    maintenance = models.CharField(max_length=100, null=True)
    rights = models.CharField(max_length=30, null=True)
    language = models.CharField(max_length=100, null=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    total_doc = models.IntegerField(null=True)
    description = models.CharField(max_length=2000, null=True)
    infor_sign = models.CharField(max_length=30, null=True)
    keyword = models.CharField(max_length=100, null=True)
    sheet_number = models.IntegerField(null=True)
    page_number = models.IntegerField(null=True)
    format = models.CharField(max_length=50, null=True)
    extra_info = models.TextField(null=True)


class Document(models.Model):
    doc_code = models.CharField(max_length=13)
    file_id = models.CharField(max_length=13)
    identifier = models.CharField(max_length=13)
    organ_id = models.CharField(max_length=13)
    file_catalog = models.IntegerField(null=True)
    file_notation = models.CharField(max_length=20)
    doc_ordinal = models.IntegerField(null=True)
    type_name = models.CharField(max_length=100)
    code_number = models.CharField(max_length=11)
    code_notation = models.CharField(max_length=30)
    issued_date = models.DateField(null=True)
    organ_name = models.CharField(max_length=200)
    subject = models.CharField(max_length=500)
    language = models.CharField(max_length=100)
    page_amount = models.IntegerField(null=True)
    description = models.CharField(max_length=500)
    infor_sign = models.CharField(max_length=30)
    keyword = models.CharField(max_length=100)
    mode = models.CharField(max_length=20)
    confidence_level = models.CharField(max_length=30)
    autograph = models.CharField(max_length=2000)
    format = models.CharField(max_length=50)
    document_path = models.CharField(max_length=1000)
    file_name = models.CharField(max_length=256)